name: Deploy Flask-SQS Service to AWS ECR

on:
  push:
    branches:
      - main
    paths:
      - 'flask-sqs-service/**'

jobs:
  build-and-push:
    name: Build and Push Flask-SQS Image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-southeast-1

      - name: Login to AWS ECR
        run: |
          aws ecr get-login-password --region ap-southeast-1 | docker login --username AWS --password-stdin ${{ secrets.255945442255 }}.dkr.ecr.ap-southeast-1.amazonaws.com

      - name: Build and Push Flask-SQS Service Image
        run: |
          docker build -t flask-sqs-service ./flask-sqs-service
          docker tag flask-sqs-service:latest ${{ secrets.255945442255 }}.dkr.ecr.ap-southeast-1.amazonaws.com/flask-sqs-service:latest
          docker push ${{ secrets.255945442255 }}.dkr.ecr.ap-southeast-1.amazonaws.com/flask-sqs-service:latest
